# Copyright 2016 Cloudbase Solutions Srl
#
# Module manifest for module 'WSFCCharmUtils'
#
# Generated by: Gabriel Adrian Samfira
#
# Generated on: 10/02/2016
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'WSFCCharmUtils.psm1'

# Version number of this module.
ModuleVersion = '0.1'

# ID used to uniquely identify this module
GUID = '14887dc1-f097-4cd1-b94f-bcfaacb35a9b'

# Author of this module
Author = 'Gabriel Adrian Samfira'

# Company or vendor of this module
CompanyName = 'Cloudbase Solutions SRL'

# Copyright statement for this module
Copyright = '(c) 2016 Cloudbase Solutions SRL. All rights reserved.'

# Description of the functionality provided by this module
Description = 'WSFC Charm utils module'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

}
