# Copyright 2015 Cloudbase Solutions Srl
#
# Module manifest for module 'S2DHooks'
#
# Generated by: Gabriel Adrian Samfira
#
# Generated on: 17/12/2015
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'S2DHooks.psm1'

# Version number of this module.
ModuleVersion = '0.1'

# ID used to uniquely identify this module
GUID = 'fdd5accf-26b0-49b9-80da-114222986d8a'

# Author of this module
Author = 'Gabriel Adrian Samfira'

# Company or vendor of this module
CompanyName = 'Cloudbase Solutions SRL'

# Copyright statement for this module
Copyright = '(c) 2015 Cloudbase Solutions SRL. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Helper module for Juju Charms'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @("JujuHelper", "JujuLoging", "powershell-yaml")

# Functions to export from this module
FunctionsToExport = @(
    "Clear-AllDisks",
    "Start-S2DRelationChangedHook",
    "Ping-S2DReady")

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

}
