#!/usr/bin/python

"""Amulet tests on a basic Glance deployment on trusty-icehouse."""

from basic_deployment import GlanceBasicDeployment

if __name__ == '__main__':
    deployment = GlanceBasicDeployment(series='trusty')
    deployment.run_tests()
