#!/usr/bin/python

"""Amulet tests on a basic glance deployment on wily-liberty."""

from basic_deployment import GlanceBasicDeployment

if __name__ == '__main__':
    deployment = GlanceBasicDeployment(series='wily')
    deployment.run_tests()
