options:
  storage-pool:
    type: string
    default: "s2d"
    description: "Storage pool name"
  volume-name:
    type: string
    default: s2dvolume
    description: "Name of volume inside S2D"
  scaleout-name:
    type: string
    default: s2dscaleout
    description: "Friendly name of scale out file server"
  minimum-nodes:
    type: int
    default: 4
    description: "Minimum number of nodes to wait for before starting cluster operations"
