#
# Copyright 2016 Cloudbase Solutions Srl
#
# Module manifest for module 'S2DUtils'
#
# Generated by: Gabriel Adrian Samfira
#
# Generated on: 13/1/2016
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'S2DUtils.psm1'

# Version number of this module.
ModuleVersion = '0.1'

# ID used to uniquely identify this module
GUID = 'b8d1a9b1-39c0-43de-9ea8-e75c6adbb35e'

# Author of this module
Author = 'Gabriel Adrian Samfira'

# Company or vendor of this module
CompanyName = 'Cloudbase Solutions SRL'

# Copyright statement for this module
Copyright = '(c) 2016 Cloudbase Solutions SRL. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Utilities for s2d'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

FunctionsToExport = 'Start-ProcessAsUser'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

RequiredModules = @("JujuWindowsUtils")

}
