#!/usr/bin/python

"""Amulet tests on a basic quantum-gateway deployment on precise-icehouse."""

from basic_deployment import NeutronGatewayBasicDeployment

if __name__ == '__main__':
    deployment = NeutronGatewayBasicDeployment(series='precise',
                                        openstack='cloud:precise-icehouse',
                                        source='cloud:precise-updates/icehouse')
    deployment.run_tests()
