#!/usr/bin/python

"""Amulet tests on a basic quantum-gateway deployment on trusty-icehouse."""

from basic_deployment import NeutronGatewayBasicDeployment

if __name__ == '__main__':
    deployment = NeutronGatewayBasicDeployment(series='trusty')
    deployment.run_tests()
