#!/usr/bin/python

"""Amulet tests on a basic quantum-gateway deployment on trusty-juno."""

from basic_deployment import NeutronGatewayBasicDeployment

if __name__ == '__main__':
    deployment = NeutronGatewayBasicDeployment(series='trusty',
                                               openstack='cloud:trusty-juno',
                                               source='cloud:trusty-updates/juno')
    deployment.run_tests()
