#!/usr/bin/python

"""Amulet tests on a basic quantum-gateway deployment on trusty-kilo."""

from basic_deployment import NeutronGatewayBasicDeployment

if __name__ == '__main__':
    deployment = NeutronGatewayBasicDeployment(series='trusty',
                                        openstack='cloud:trusty-kilo',
                                        source='cloud:trusty-updates/kilo')
    deployment.run_tests()
