#!/usr/bin/python

"""Amulet tests on a basic quantum-gateway deployment on vivid-kilo."""

from basic_deployment import NeutronGatewayBasicDeployment

if __name__ == '__main__':
    deployment = NeutronGatewayBasicDeployment(series='vivid')
    deployment.run_tests()
