#!/usr/bin/python

"""Amulet tests on a basic quantum-gateway deployment on trusty-liberty."""

from basic_deployment import NeutronGatewayBasicDeployment

if __name__ == '__main__':
    deployment = NeutronGatewayBasicDeployment(series='trusty',
                                               openstack='cloud:trusty-liberty',
                                               source='cloud:trusty-updates/liberty')
    deployment.run_tests()
