#!/usr/bin/python

"""Amulet tests on a basic quantum-gateway deployment on wily-liberty."""

from basic_deployment import NeutronGatewayBasicDeployment

if __name__ == '__main__':
    deployment = NeutronGatewayBasicDeployment(series='wily')
    deployment.run_tests()
