#!/usr/bin/python

"""Amulet tests on a basic neutron-gateway git deployment on trusty-kilo."""

from basic_deployment import NeutronGatewayBasicDeployment

if __name__ == '__main__':
    deployment = NeutronGatewayBasicDeployment(series='trusty',
                                               openstack='cloud:trusty-kilo',
                                               source='cloud:trusty-updates/kilo',
                                               git=True)
    deployment.run_tests()
