#!/usr/bin/python

"""Amulet tests on a basic openstack-dashboard deployment on precise-icehouse."""

from basic_deployment import OpenstackDashboardBasicDeployment

if __name__ == '__main__':
    deployment = OpenstackDashboardBasicDeployment(series='precise',
                                                   openstack='cloud:precise-icehouse',
                                                   source='cloud:precise-updates/icehouse')
    deployment.run_tests()
