#!/usr/bin/python

"""Amulet tests on a basic openstack-dashboard deployment on trusty-juno."""

from basic_deployment import OpenstackDashboardBasicDeployment

if __name__ == '__main__':
    deployment = OpenstackDashboardBasicDeployment(series='trusty',
                                                   openstack='cloud:trusty-juno',
                                                   source='cloud:trusty-updates/juno')
    deployment.run_tests()
