#!/usr/bin/python

"""Amulet tests on a basic openstack-dashboard deployment on vivid-kilo."""

from basic_deployment import OpenstackDashboardBasicDeployment

if __name__ == '__main__':
    deployment = OpenstackDashboardBasicDeployment(series='vivid')
    deployment.run_tests()
