#!/usr/bin/python

"""Amulet tests on a basic openstack-dashboard git deployment on trusty-icehouse."""

from basic_deployment import OpenstackDashboardBasicDeployment

if __name__ == '__main__':
    deployment = OpenstackDashboardBasicDeployment(series='trusty', git=True)
    deployment.run_tests()
