#!/usr/bin/python

"""Amulet tests on a basic openstack-dashboard git deployment on trusty-kilo."""

from basic_deployment import OpenstackDashboardBasicDeployment

if __name__ == '__main__':
    deployment = OpenstackDashboardBasicDeployment(series='trusty',
                                                   openstack='cloud:trusty-kilo',
                                                   source='cloud:trusty-updates/kilo',
                                                   git=True)
    deployment.run_tests()
