#!/usr/bin/python

"""Amulet tests on a basic keystone deployment on vivid-kilo."""

from basic_deployment import KeystoneBasicDeployment

if __name__ == '__main__':
    deployment = KeystoneBasicDeployment(series='vivid')
    deployment.run_tests()
