#!/usr/bin/python

"""Amulet tests on a basic keystone deployment on trusty-liberty."""

from basic_deployment import KeystoneBasicDeployment

if __name__ == '__main__':
    deployment = KeystoneBasicDeployment(series='trusty',
                                         openstack='cloud:trusty-liberty',
                                         source='cloud:trusty-updates/liberty')
    deployment.run_tests()
