#!/usr/bin/python

"""Amulet tests on a basic keystone deployment on wily-liberty."""

from basic_deployment import KeystoneBasicDeployment

if __name__ == '__main__':
    deployment = KeystoneBasicDeployment(series='wily')
    deployment.run_tests()
