#!/usr/bin/python

"""Amulet tests on a basic keystone git deployment on trusty-kilo."""

from basic_deployment import KeystoneBasicDeployment

if __name__ == '__main__':
    deployment = KeystoneBasicDeployment(series='trusty',
                                         openstack='cloud:trusty-kilo',
                                         source='cloud:trusty-updates/kilo',
                                         git=True)
    deployment.run_tests()
