#!/usr/bin/python

"""Amulet tests on a basic neutron-api deployment on precise-icehouse."""

from basic_deployment import NeutronAPIBasicDeployment

if __name__ == '__main__':
    deployment = NeutronAPIBasicDeployment(series='precise',
                                           openstack='cloud:precise-icehouse',
                                           source='cloud:precise-updates/icehouse')
    deployment.run_tests()
