#!/usr/bin/python

"""Amulet tests on a basic neutron-api deployment on trusty-icehouse."""

from basic_deployment import NeutronAPIBasicDeployment

if __name__ == '__main__':
    deployment = NeutronAPIBasicDeployment(series='trusty')
    deployment.run_tests()
