#!/usr/bin/python

"""Amulet tests on a basic neutron-api deployment on trusty-kilo."""

from basic_deployment import NeutronAPIBasicDeployment

if __name__ == '__main__':
    deployment = NeutronAPIBasicDeployment(series='trusty',
                                           openstack='cloud:trusty-kilo',
                                           source='cloud:trusty-updates/kilo')
    deployment.run_tests()
