#!/usr/bin/python

"""Amulet tests on a basic neutron-api deployment on vivid-kilo."""

from basic_deployment import NeutronAPIBasicDeployment

if __name__ == '__main__':
    deployment = NeutronAPIBasicDeployment(series='vivid')
    deployment.run_tests()
