#!/usr/bin/python

"""Amulet tests on a basic neutron-api deployment on wily-liberty."""

from basic_deployment import NeutronAPIBasicDeployment

if __name__ == '__main__':
    deployment = NeutronAPIBasicDeployment(series='wily')
    deployment.run_tests()
