#!/usr/bin/python

"""Amulet tests on a basic neutron-api git deployment on trusty-juno."""

from basic_deployment import NeutronAPIBasicDeployment

if __name__ == '__main__':
    deployment = NeutronAPIBasicDeployment(series='trusty',
                                           openstack='cloud:trusty-juno',
                                           source='cloud:trusty-updates/juno',
                                           git=True)
    deployment.run_tests()
