#!/usr/bin/python

"""Amulet tests on a basic neutron-api git deployment on trusty-kilo."""

from basic_deployment import NeutronAPIBasicDeployment

if __name__ == '__main__':
    deployment = NeutronAPIBasicDeployment(series='trusty',
                                           openstack='cloud:trusty-kilo',
                                           source='cloud:trusty-updates/kilo',
                                           git=True)
    deployment.run_tests()
