#!/usr/bin/python

"""Amulet tests on a basic nova compute deployment on precise-icehouse."""

from basic_deployment import NovaBasicDeployment

if __name__ == '__main__':
    deployment = NovaBasicDeployment(series='precise',
                                     openstack='cloud:precise-icehouse',
                                     source='cloud:precise-updates/icehouse')
    deployment.run_tests()
