#!/usr/bin/python

"""Amulet tests on a basic nova compute deployment on trusty-icehouse."""

from basic_deployment import NovaBasicDeployment

if __name__ == '__main__':
    deployment = NovaBasicDeployment(series='trusty')
    deployment.run_tests()
