#!/usr/bin/python

"""Amulet tests on a basic nova compute deployment on vivid-kilo."""

from basic_deployment import NovaBasicDeployment

if __name__ == '__main__':
    deployment = NovaBasicDeployment(series='vivid')
    deployment.run_tests()
