#!/usr/bin/python

"""Amulet tests on a basic nova compute git deployment on trusty-icehouse."""

from basic_deployment import NovaBasicDeployment

if __name__ == '__main__':
    deployment = NovaBasicDeployment(series='trusty', git=True)
    deployment.run_tests()
