#!/usr/bin/python

"""Amulet tests on a basic nova compute git deployment on trusty-juno."""

from basic_deployment import NovaBasicDeployment

if __name__ == '__main__':
    deployment = NovaBasicDeployment(series='trusty',
                                     openstack='cloud:trusty-juno',
                                     source='cloud:trusty-updates/juno',
                                     git=True)
    deployment.run_tests()
