#
# Copyright 2014-2015 Cloudbase Solutions Srl
#
# Module manifest for module 'ADHooks'
#
# Generated by: Gabriel Adrian Samfira
#
# Generated on: 17/12/2015
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'ADHooks.psm1'

# Version number of this module.
ModuleVersion = '0.1'

# ID used to uniquely identify this module
GUID = 'c62a061b-cfa2-4a0b-aecc-9ffc26a59050'

# Author of this module
Author = 'Gabriel Adrian Samfira','Adrian Vladu'

# Company or vendor of this module
CompanyName = 'Cloudbase Solutions SRL'

# Copyright statement for this module
Copyright = '(c) 2015 Cloudbase Solutions SRL. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Hook functions  for active directory charm'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

FunctionsToExport = @(
    "Start-TimeResync",
    "Start-InstallHook",
    "Start-StopHook",
    "Start-UpgradeCharmHook",
    "Start-LeaderElectedHook",
    "Start-ADRelationChangedHook",
    "Start-AddControllerRelationJoinedHook",
    "Start-AddControllerRelationChangedHook",
    "Start-ADRelationJoinedHook",
    "Start-ADRelationDepartedHook")

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

RequiredModules = @(
    "JujuWindowsUtils",
    "JujuLogging",
    "JujuHooks",
    "JujuUtils",
    "ADCharmUtils")

}
