#
# Copyright 2016 Cloudbase Solutions Srl
#
# Module manifest for module 'ADCharmUtils'
#
# Generated by: Gabriel Adrian Samfira
#
# Generated on: 17/12/2015
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'ADCharmUtils.psm1'

# Version number of this module.
ModuleVersion = '0.1'

# ID used to uniquely identify this module
GUID = '3939221f-f696-44a0-b6c0-21c5648aa2ed'

# Author of this module
Author = 'Gabriel Adrian Samfira','Adrian Vladu'

# Company or vendor of this module
CompanyName = 'Cloudbase Solutions SRL'

# Copyright statement for this module
Copyright = '(c) 2015 Cloudbase Solutions SRL. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Utilities for active directory charm'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

FunctionsToExport = '*'

RequiredModules = @("JujuWindowsUtils", "JujuLogging", "JujuHooks", "JujuUtils")

}
