#!/usr/bin/python

"""Amulet tests on a basic neutron-openvswitch deployment on trusty-icehouse."""

from basic_deployment import NeutronOVSBasicDeployment

if __name__ == '__main__':
    deployment = NeutronOVSBasicDeployment(series='trusty')
    deployment.run_tests()
