#!/usr/bin/python

"""Amulet tests on a basic neutron-openvswitch git deployment on trusty-kilo."""

from basic_deployment import NeutronOVSBasicDeployment

if __name__ == '__main__':
    deployment = NeutronOVSBasicDeployment(series='trusty',
                                           openstack='cloud:trusty-kilo',
                                           source='cloud:trusty-updates/kilo',
                                           git=True)
    deployment.run_tests()
