#!/usr/bin/python

"""Amulet tests on a basic nova cloud controller deployment on
   precise-essex."""

from basic_deployment import NovaCCBasicDeployment

if __name__ == '__main__':
    deployment = NovaCCBasicDeployment(series='precise')
    deployment.run_tests()
