#!/usr/bin/python

"""Amulet tests on a basic nova cloud controller deployment on
   trusty-kilo."""

from basic_deployment import NovaCCBasicDeployment

if __name__ == '__main__':
    deployment = NovaCCBasicDeployment(series='trusty',
                                       openstack='cloud:trusty-kilo',
                                       source='cloud:trusty-updates/kilo')
    deployment.run_tests()
