#!/usr/bin/python

"""Amulet tests on a basic nova cloud controller deployment on
   trusty-liberty."""

from basic_deployment import NovaCCBasicDeployment

if __name__ == '__main__':
    deployment = NovaCCBasicDeployment(series='trusty',
                                       openstack='cloud:trusty-liberty',
                                       source='cloud:trusty-updates/liberty')
    deployment.run_tests()
