#!/usr/bin/python

"""Amulet tests on a basic nova cloud controller deployment on
   wily-liberty."""

from basic_deployment import NovaCCBasicDeployment

if __name__ == '__main__':
    deployment = NovaCCBasicDeployment(series='wily')
    deployment.run_tests()
