#!/usr/bin/python

"""Amulet tests on a basic nova-cloud-controller git deployment on trusty-kilo."""

from basic_deployment import NovaCCBasicDeployment

if __name__ == '__main__':
    deployment = NovaCCBasicDeployment(series='trusty',
                                       openstack='cloud:trusty-kilo',
                                       source='cloud:trusty-updates/kilo',
                                       git=True)
    deployment.run_tests()
